project_name: sketchversion

builds:
  - binary: sketchversion
    goos:
      - windows
      - darwin
      - linux
      - freebsd
      - openbsd
      - solaris
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: openbsd
        goarch: arm

brew:
  github:
    owner: wyattjoh
    name: homebrew-stable
  folder: Formula
  homepage:  https://github.com/wyattjoh/sketchversion
  description: Utility to download the most recent Sketch version based on your valid license.
  test: |
    system "#{bin}/sketchversion -v"

archive:
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
    - LICENSE.md
    - README.md

release:
  github:
    owner: wyattjoh
    name: sketchversion